name: jlabtutorial
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - cookiecutter
  - notebook
  - pandas=0.24
  - nodejs
  - jupyterlab=1
  - bqplot
  - ipyleaflet
  - ipympl
  - ipyvolume
  - pythreejs
